name: llm_dart
description: A modular Dart library for AI provider interactions with unified interface for OpenAI, Anthropic, Google, DeepSeek, Ollama, xAI, Groq, ElevenLabs and more.
version: 0.1.0
license: MIT
homepage: https://github.com/Latias94/yumcha/tree/main/packages/llm_dart
repository: https://github.com/Latias94/yumcha
issue_tracker: https://github.com/Latias94/yumcha/issues

topics:
  - ai
  - llms
  - nlp

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.8.0"

dependencies:
  dio: ^5.8.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  mockito: ^5.4.0
